
import { hrService } from './hrService';
import { Attendance } from '../types';

export const reportsEmailService = {
  /**
   * Formats and queues a professional Attendance Audit Report.
   * Optimized for size to fit within PocketBase's 5000 char limit per record.
   */
  async sendAttendanceAudit(recipientEmail: string, attendance: Attendance[], subjectSuffix: string = '') {
    if (attendance.length === 0) {
      throw new Error("Cannot send report: No attendance records found for the selected period.");
    }

    console.log(`[reportsEmailService] Preparing Attendance Audit for: ${recipientEmail} with ${attendance.length} records.`);

    // Get date range from records if possible
    const dates = attendance.map(a => a.date).sort();
    const rangeStr = dates.length > 1 
      ? `${dates[0]} to ${dates[dates.length - 1]}`
      : dates[0] || new Date().toISOString().split('T')[0];

    const sortedAttendance = [...attendance].sort((a, b) => 
      (a.employeeName || '').localeCompare(b.employeeName || '')
    );

    // Optimized Row Generation (Minified HTML)
    const rows = sortedAttendance.map((a, index) => {
      const rowClass = index % 2 === 0 ? 'r0' : 'r1';
      const statusClass = `s-${a.status}`;
      // Truncate name if too long to save space
      const name = (a.employeeName || 'Unknown').substring(0, 20);
      
      return `<tr class="${rowClass}"><td class="d">${name}</td><td class="d m">${a.checkIn || '-'}</td><td class="d m">${a.checkOut || '-'}</td><td class="d r"><span class="b ${statusClass}">${a.status.substring(0,3)}</span></td></tr>`;
    }).join('');

    // Minified HTML Structure with embedded CSS
    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #1e293b; font-size: 12px; }
          .w { max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden; }
          .h { background: #0f172a; color: white; padding: 15px; text-align: center; }
          .h h1 { margin: 0; font-size: 16px; text-transform: uppercase; letter-spacing: 1px; }
          .h p { margin: 5px 0 0; font-size: 10px; color: #94a3b8; }
          table { width: 100%; border-collapse: collapse; }
          th { background: #f1f5f9; padding: 8px; font-size: 10px; text-align: left; text-transform: uppercase; color: #64748b; }
          .d { padding: 8px; border-bottom: 1px solid #f1f5f9; }
          .m { font-family: monospace; color: #475569; }
          .r { text-align: right; }
          .b { padding: 2px 6px; border-radius: 4px; font-size: 9px; font-weight: bold; }
          .r0 { background: #ffffff; }
          .r1 { background: #f8fafc; }
          .s-LATE { color: #d97706; background: #fef3c7; }
          .s-ABSENT { color: #dc2626; background: #fee2e2; }
          .s-PRESENT { color: #059669; background: #d1fae5; }
          .f { background: #f8fafc; padding: 10px; text-align: center; font-size: 9px; color: #94a3b8; border-top: 1px solid #e2e8f0; }
        </style>
      </head>
      <body>
        <div class="w">
          <div class="h">
            <h1>Attendance Audit</h1>
            <p>${rangeStr} • ${attendance.length} Records${subjectSuffix}</p>
          </div>
          <table>
            <tr><th>Name</th><th>In</th><th>Out</th><th class="r">Stat</th></tr>
            ${rows}
          </table>
          <div class="f">Generated by OpenHR • Part of secure audit trail</div>
        </div>
      </body>
      </html>
    `.replace(/\s+/g, ' ').trim(); // Simple minification

    try {
      const result = await hrService.sendCustomEmail({ 
        recipientEmail, 
        subject: `[Report] ${rangeStr}${subjectSuffix}`,
        html,
        type: 'SYSTEM_REPORT'
      });
      console.log("[reportsEmailService] Success queuing email:", result);
      return result;
    } catch (err) {
      console.error("[reportsEmailService] Error dispatching to hrService:", err);
      throw err;
    }
  }
};
